main: de.keule.gh.main.GHPlugin
name: GrapplingHook
author: Keule2
version: 2.6
description: Grappling Hook Plugin
api-version: 1.13
softdepend: [WorldGuard]

commands:
    grapplinghook:
        aliases: [gh]