#A list of all sounds(not all working) https://github.com/Attano/Spigot-1.8/blob/master/org/bukkit/Sound.java

#The grapplingHookName is the name of the grappling hook when you craft it 
Plugin:
   prefix: "&7[&6Enterhaken&7] "
   grapplingHookName: "&6Grappling hook"
   useAir: false
   useInAllWorlds: false
   crafting: false
   cooldown: 2.0
   
Messages:
   reload: "%prefix%&7Die Config wurde neu geladen."
   noperm: "%prefix%&4Dazu hast du keine Rechte."
   unknownCMD: "%prefix%&7Diesen Command gibt es nicht oder falsche Syntax."
   onlyNumbers: "%prefix%&4Nur Zahlen eingeben!"
   useInAllWorlds: "%prefix%&7Nun ist der Enterhaken in allen Welten aktiv."
   useInIndividualWorlds: "%prefix%&7Nun kannst du den Enterhaken wieder mit setworld festlegen."
   setSound: "%prefix%&7Du hast den Sound(%sound%) gesetzt."
   setWorld: "%prefix%&2Die Welt(%world%) wurde der Liste hinzugefuegt."
   removeWorld: "%prefix%&4Du hast die Welt(%world%) aus der Liste entfernt."
   alreadyInList: "%prefix%&7Diese Welt(%world%) ist bereits in deiner Liste."
   isNotInList: "%prefix%&7Diese Welt(%world%) ist nicht in deiner Liste."
   cooldown: "%prefix%&7Einen Moment noch!(%timeLeft%s)"
   setCooldown: "%prefix%&7Der Cooldown btraegt nun %newTime%s"
   useAir: "%prefix%&7UseAir ist nun %state%"
   crafting: "%prefix%&7Crafting ist nun %state%"
   
Sound:
   grapplinghookSound: ENTITY_ENDERMEN_TELEPORT

#To take affect the whole server must be reload or retsart
Recipe:
   slot1: ""
   slot2: ""
   slot3: "Stick"
   slot4: ""
   slot5: "Stick"
   slot6: "String"
   slot7: "Stick"
   slot8: ""
   slot9: "Iron_Ingot"

#All worlds where the grappling hook is active are in this list
WorldList: []